



# Webserver container with CGI python script
# Using RHEL 7 base image and Apache Web server
# Version 1

# Pull the rhel image from the local repository
FROM ubuntu:14.10
USER root


MAINTAINER Karthik


# Update image
RUN apt-get update
UN yum -y install http


